name: eShopOnWeb Build and Test

on: [push, workflow_dispatch]

env:
  RESOURCE_GROUP: rg-eshoponweb-rishi
  LOCATION: eastus
  TEMPLATE_FILE: infra/webapp.bicep
  SUBSCRIPTION_ID: 736a1b54-3f52-4444-869c-07b70e15231b
  WEBAPP_NAME: eshoponweb-webapp-rishi4545

jobs:
  # Build, test and publish .NET web project in repository
  buildandtest:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4
      
      # Prepare runner for desired .NET version SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          dotnet-quality: 'preview'
      
      # Build/Test/Publish the .NET project
      - name: Build with dotnet
        run: dotnet build ./eShopOnWeb.sln --configuration Release
      
      - name: Test with dotnet
        run: dotnet test ./eShopOnWeb.sln --configuration Release
      
      - name: Dotnet publish
        run: |
          dotnet publish ./src/Web/Web.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp
          cd ${{env.DOTNET_ROOT}}/myapp
          zip -r ../app.zip .
      
      # Upload the published website code artifacts
      - name: Upload artifact for deployment job (code)
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/app.zip
      
      # Upload the Bicep template as artifacts for the next job
      - name: Upload artifact for deployment job (template)
        uses: actions/upload-artifact@v4
        with:
          name: bicep-template
          path: ${{ env.TEMPLATE_FILE }}
        
  # Use Bicep to deploy infrastructure + Publish webapp 
  deploy:
    runs-on: ubuntu-latest
    needs: buildandtest
    environment:
      name: 'Development'
    steps:
      # Download the publish files created in the previous job
      - name: Download artifact from build job (code)
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: .net-app
  
      # Download the Bicep templates from the previous job
      - name: Download artifact from build job (template)
        uses: actions/download-artifact@v4
        with:
          name: bicep-template
          path: bicep-template
        
      # Login to your Azure subscription using a service principal (credentials stored as GitHub Secret in repo)
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
           
      # Deploy Azure WebApp using Bicep file
      - name: Deploy
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ env.SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.RESOURCE_GROUP }}
          template: bicep-template/webapp.bicep
          parameters: 'webAppName=${{ env.WEBAPP_NAME }} location=${{ env.LOCATION }}'
          failOnStdErr: false   
    
      # Publish website to Azure App Service (WebApp)
      # Step disabled due to issue where the site sometimes can't be found: https://github.com/microsoft/pipelines-appservice-lib/issues/56. Instead deploy using CLI
      - name: Publish Website to WebApp (GitHub Action)
        if: false # Disable step due to comment above
        uses: Azure/webapps-deploy@v3
        with:
          type: ZIP
          app-name: ${{ env.WEBAPP_NAME  }}
          package: .net-app/app.zip

      # Publish website to Azure App Service using CLI (WebApp)
      - name: Publish Website to WebApp (CLI)
        uses: Azure/cli@v2
        with:
        azcliversion: latest
          inlineScript: |
             az webapp deploy --name ${{ env.WEBAPP_NAME }} --resource-group ${{ env.RESOURCE_GROUP }} --src-path .net-app/app.zip --type zip
